# RENAME EXAMPLE TO APPLICATION FROM FILE NAME FOR IT TO WORK
spring.application.name=backend

spring.datasource.url=jdbc:postgresql://ADDRESS:PORT/SQL_SERVER_NAME
spring.datasource.username=USER
spring.datasource.password=PASSWORD

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=ACTION_TODO_WITH_DB
spring.jpa.show-sql=SHOW_SQL_IN_CONSOLE_BOOLEAN
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect